
import { LocationData, Region, Province, District, Branch } from '@/types/locations';

// Single CSV data structure - all location data in one file
interface LocationCSVRow {
  region: string;
  province: string;
  district: string;
  branch: string;
}

// Generate enhanced mock data based on the CSV example you provided
export const generateLocationMockData = (): LocationCSVRow[] => {
  const mockData: LocationCSVRow[] = [
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: '0', branch: 'สำนักพหลโยธิน' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'บางเขน' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'มหาวิทยาลัยเกษตรศาสตร์' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'จตุจักร' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'พงษ์เพชร' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'ประชาชื่น' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'เตาปูน' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'เอนเนอร์ยี่ คอมเพล็กซ์' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'มาร์เก็ต เพลส วงศ์สว่าง' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'เซ็นทรัล ลาดพร้าว' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'ประชานิเวศน์ 1' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'กรีนพลาซ่า (วังหิน)' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'อเวนิว รัชโยธิน' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'บางเขน', branch: 'ตลาด อ.ต.ก. (จตุจักร)' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ราชวัตร', branch: 'ราชวัตร' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ราชวัตร', branch: 'ศรีย่าน' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ราชวัตร', branch: 'สวนจิตรลดา' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ราชวัตร', branch: 'มหานาค' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ราชวัตร', branch: 'นางเลิ้ง' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ราชวัตร', branch: 'ทำเนียบรัฐบาล' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ราชวัตร', branch: 'ถนนประดิพัทธ์' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ราชวัตร', branch: 'สุพรีม คอมเพล็กซ์ สามเสน' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ราชวัตร', branch: 'แยกพิชัย' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'สะพานใหม่' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'ดอนเมือง' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'ตลาดวงศกร' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'อนุสรณ์สถานแห่งชาติ' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'ตลาดยิ่งเจริญ ' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'ถนนสรงประภา' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'ศูนย์ราชการเฉลิมพระเกียรติ แจ้งวัฒนะ (อาคาร B)' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'ไอที สแควร์' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'กรมการกงสุล' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'บิ๊กซี แจ้งวัฒนะ ' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'ศูนย์ราชการเฉลิมพระเกียรติ แจ้งวัฒนะ (อาคาร A)' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'วัชรพล' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'สะพานใหม่', branch: 'เดอะแจส รามอินทรา' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ห้วยขวาง', branch: 'ห้วยขวาง' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ห้วยขวาง', branch: 'ยุติธรรม' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ห้วยขวาง', branch: 'ชัยสมรภูมิ' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ห้วยขวาง', branch: 'ดินแดง' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ห้วยขวาง', branch: 'ลาดพร้าว' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ห้วยขวาง', branch: 'กระทรวงการคลัง' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ห้วยขวาง', branch: 'เอสพละนาด รัชดาภิเษก' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ห้วยขวาง', branch: 'อีสท์วอเตอร์' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ห้วยขวาง', branch: 'เซ็นทรัล พระราม 9' },
  { region: 'ภาค 1', province: 'กรุงเทพฯ', district: 'ห้วยขวาง', branch: 'บิ๊กซี ลาดพร้าว 2' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'คลองจั่น', branch: 'คลองจั่น' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'คลองจั่น', branch: 'โชคชัย 4' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'คลองจั่น', branch: 'รามอินทรา กม.7' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'คลองจั่น', branch: 'เดอะมอลล์ บางกะปิ' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'คลองจั่น', branch: 'เซ็นทรัล รามอินทรา' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'คลองจั่น', branch: 'สัมมากร เพลส รามคำแหง 110' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'คลองจั่น', branch: 'เดอะพาซิโอ ทาวน์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'คลองจั่น', branch: 'ลาดพร้าว 101' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'คลองจั่น', branch: 'เซ็นทรัล อีสต์วิลล์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'คลองจั่น', branch: 'เดอะคริสตัล' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'มีนบุรี', branch: 'หนองจอก' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'มีนบุรี', branch: 'มีนบุรี' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'มีนบุรี', branch: 'ลาดกระบัง' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'มีนบุรี', branch: 'เดอะพรอมานาด' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'มีนบุรี', branch: 'บิ๊กซี เคหะร่มเกล้า' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'มีนบุรี', branch: 'บิ๊กซี หทัยราษฎร์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'มีนบุรี', branch: 'แฟชั่นไอส์แลนด์ 2' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'มีนบุรี', branch: 'ไอเพลส นิคมอุตสาหกรรมลาดกระบัง' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'มีนบุรี', branch: 'บิ๊กซี สุวินทวงศ์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'ถนนเพชรบุรี', branch: 'ถนนเพชรบุรี' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'ถนนเพชรบุรี', branch: 'เจริญผล' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'ถนนเพชรบุรี', branch: 'ป้อมปราบ' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'ถนนเพชรบุรี', branch: 'อุรุพงษ์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'ถนนเพชรบุรี', branch: 'วรจักร' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'ถนนเพชรบุรี', branch: 'จักรวรรดิ' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'ถนนเพชรบุรี', branch: 'สยามพารากอน ' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'ถนนเพชรบุรี', branch: 'ฟีนิกซ์ ' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'ถนนเพชรบุรี', branch: 'มาบุญครอง' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'บางรัก', branch: 'บางรัก' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'บางรัก', branch: 'หัวลำโพง' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'บางรัก', branch: 'สาทร' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'บางรัก', branch: 'ถนนจันทน์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'บางรัก', branch: 'สีลม' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'บางรัก', branch: 'เยาวราช' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'บางรัก', branch: 'แอทสาทร ' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พร้อมพงษ์', branch: 'พร้อมพงษ์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พร้อมพงษ์', branch: 'คลองเตย' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พร้อมพงษ์', branch: 'ราชประสงค์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พร้อมพงษ์', branch: 'สามย่าน' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พร้อมพงษ์', branch: 'จามจุรีสแควร์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พร้อมพงษ์', branch: 'ทองหล่อ' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พร้อมพงษ์', branch: 'เซ็นทรัลเวิลด์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พร้อมพงษ์', branch: 'เกทเวย์ เอกมัย' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พร้อมพงษ์', branch: 'โลตัส พระราม 4' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'พระโขนง' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'คลองตัน' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'รามคำแหง 2' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'รามคำแหง' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'บางนา' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'หัวหมาก' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'พาราไดซ์ พาร์ค' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'ซีคอนสแควร์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: ' ปตท.ประเวศ' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'เดอะซีน ทาวน์ อิน ทาวน์' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'เซ็นทรัล บางนา' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'ไบเทค บางนา (เซ็นทรัล บางนา)' },
  { region: 'ภาค 2', province: 'กรุงเทพฯ', district: 'พระโขนง', branch: 'เดอะไนน์ พระราม 9' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางคอแหลม', branch: 'บางคอแหลม' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางคอแหลม', branch: 'ทุ่งมหาเมฆ' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางคอแหลม', branch: 'สาธุประดิษฐ์' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางคอแหลม', branch: 'บางโพงพาง' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ราษฎร์บูรณะ', branch: 'ดาวคะนอง' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางคอแหลม', branch: 'ทรี ออน ธรี' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางคอแหลม', branch: 'เซ็นทรัล พระราม 3' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางคอแหลม', branch: 'ศูนย์การค้ากรีนเพลส พลาซา' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางคอแหลม', branch: 'เจริญกรุง 107 (แฉล้มนิมิตร)' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'บางแค' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'ตลิ่งชัน' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ศิริราช', branch: 'บางพลัด' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'หมู่บ้านเศรษฐกิจ' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'ขนส่งสายใต้' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'เดอะมอลล์ บางแค' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'สี่แยกทศกัณฐ์' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'สวนผัก' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'เดอะพาซิโอ พาร์ค กาญจนาภิเษก' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'หนองแขม' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'ซีคอน บางแค' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ศิริราช', branch: 'มหาดไทย' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ศิริราช', branch: 'หน้าพระลาน' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ศิริราช', branch: 'บางลำภูบน' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ศิริราช', branch: 'เทเวศร์' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ศิริราช', branch: 'ปากคลองตลาด' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ราษฎร์บูรณะ', branch: 'ราษฎร์บูรณะ' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ราษฎร์บูรณะ', branch: 'วงเวียนใหญ่' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางคอแหลม', branch: 'สมเด็จเจ้าพระยา' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางคอแหลม', branch: 'เจริญนคร' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ราษฎร์บูรณะ', branch: 'วัดไทร' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ราษฎร์บูรณะ', branch: 'พระราม 2 ซอย 64' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ราษฎร์บูรณะ', branch: 'ทุ่งครุ' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ราษฎร์บูรณะ', branch: 'ถนนบางขุนเทียน - ชายทะเล' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ราษฎร์บูรณะ', branch: 'บิ๊กซี พระราม 2' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ราษฎร์บูรณะ', branch: 'บิ๊กซี บางปะกอก' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ราษฎร์บูรณะ', branch: 'บางบอน (ตลาดปิ่นทอง)' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ราษฎร์บูรณะ', branch: 'เซ็นทรัล พระราม 2' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางคอแหลม', branch: 'ไอคอนสยาม' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ศิริราช', branch: 'ศิริราช' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'ตลาดพลู' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'ท่าพระ' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'บางแค', branch: 'จรัญสนิทวงศ์' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ศิริราช', branch: 'เจริญพาศน์' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ศิริราช', branch: 'เดอะมอลล์ ท่าพระ' },
  { region: 'ภาค 3', province: 'กรุงเทพฯ', district: 'ศิริราช', branch: 'เซ็นทรัล ปิ่นเกล้า' },
  { region: 'ภาค 4', province: 'ประจวบคีรีขันธ์', district: 'ประจวบคีรีขันธ์', branch: 'ประจวบคีรีขันธ์' },
  { region: 'ภาค 4', province: 'ประจวบคีรีขันธ์', district: 'ประจวบคีรีขันธ์', branch: 'หัวหิน' },
  { region: 'ภาค 4', province: 'ประจวบคีรีขันธ์', district: 'ประจวบคีรีขันธ์', branch: 'ทับสะแก' },
  { region: 'ภาค 4', province: 'ประจวบคีรีขันธ์', district: 'ประจวบคีรีขันธ์', branch: 'ค่ายธนะรัชต์' },
  { region: 'ภาค 4', province: 'ประจวบคีรีขันธ์', district: 'ประจวบคีรีขันธ์', branch: 'บางสะพาน' },
  { region: 'ภาค 4', province: 'ประจวบคีรีขันธ์', district: 'ประจวบคีรีขันธ์', branch: 'ปราณบุรี' },
  { region: 'ภาค 4', province: 'ประจวบคีรีขันธ์', district: 'ประจวบคีรีขันธ์', branch: 'กุยบุรี' },
  { region: 'ภาค 4', province: 'ประจวบคีรีขันธ์', district: 'ประจวบคีรีขันธ์', branch: 'สามร้อยยอด' },
  { region: 'ภาค 4', province: 'ประจวบคีรีขันธ์', district: 'ประจวบคีรีขันธ์', branch: 'ตลาดฉัตรไชย (หัวหิน)' },
  { region: 'ภาค 4', province: 'ประจวบคีรีขันธ์', district: 'ประจวบคีรีขันธ์', branch: 'ปากน้ำปราณ' },
  { region: 'ภาค 4', province: 'ประจวบคีรีขันธ์', district: 'ประจวบคีรีขันธ์', branch: 'บางสะพานน้อย' },
  { region: 'ภาค 4', province: 'เพชรบุรี', district: 'เพชรบุรี', branch: 'เพชรบุรี' },
  { region: 'ภาค 4', province: 'เพชรบุรี', district: 'เพชรบุรี', branch: 'ท่ายาง' },
  { region: 'ภาค 4', province: 'เพชรบุรี', district: 'เพชรบุรี', branch: 'บ้านแหลม' },
  { region: 'ภาค 4', province: 'เพชรบุรี', district: 'เพชรบุรี', branch: 'ชะอำ' },
  { region: 'ภาค 4', province: 'เพชรบุรี', district: 'เพชรบุรี', branch: 'เขาย้อย' },
  { region: 'ภาค 4', province: 'เพชรบุรี', district: 'เพชรบุรี', branch: 'สะพานจอมเกล้า' },
  { region: 'ภาค 4', province: 'เพชรบุรี', district: 'เพชรบุรี', branch: 'หนองหญ้าปล้อง' },
  { region: 'ภาค 4', province: 'เพชรบุรี', district: 'เพชรบุรี', branch: 'แก่งกระจาน' },
  { region: 'ภาค 4', province: 'เพชรบุรี', district: 'เพชรบุรี', branch: 'บ้านลาด' },
  { region: 'ภาค 4', province: 'เพชรบุรี', district: 'เพชรบุรี', branch: 'โรบินสัน เพชรบุรี' },
  { region: 'ภาค 4', province: 'เพชรบุรี', district: 'เพชรบุรี', branch: 'มหาวิทยาลัยราชภัฎเพชรบุรี  (สะพานจอมเกล้า)' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'ราชบุรี' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'บ้านโป่ง' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'โพธาราม' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'ดำเนินสะดวก' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'ปากท่อ' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'จอมบึง' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'บางแพ' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'สวนผึ้ง' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'ศรีสุริยวงศ์' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'รอยัลพาร์ค' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'บิ๊กซี บ้านโป่ง' },
  { region: 'ภาค 4', province: 'ราชบุรี', district: 'ราชบุรี', branch: 'วัดเพลง' },
  { region: 'ภาค 4', province: 'สมุทรสาคร', district: 'สมุทรสาคร', branch: 'สมุทรสาคร' },
  { region: 'ภาค 4', province: 'สมุทรสาคร', district: 'สมุทรสาคร', branch: 'กระทุ่มแบน' },
  { region: 'ภาค 4', province: 'สมุทรสาคร', district: 'สมุทรสาคร', branch: 'บ้านแพ้ว' },
  { region: 'ภาค 4', province: 'สมุทรสาคร', district: 'สมุทรสาคร', branch: 'มหาชัย' },
  { region: 'ภาค 4', province: 'สมุทรสาคร', district: 'สมุทรสาคร', branch: 'โพธิ์แจ้' },
  { region: 'ภาค 4', province: 'สมุทรสาคร', district: 'สมุทรสาคร', branch: 'พันท้ายนรสิงห์' },
  { region: 'ภาค 4', province: 'สมุทรสาคร', district: 'สมุทรสาคร', branch: 'ถนนเศรษฐกิจ 1' },
  { region: 'ภาค 4', province: 'สมุทรสาคร', district: 'สมุทรสาคร', branch: 'เซ็นทรัล มหาชัย' },
  { region: 'ภาค 4', province: 'สมุทรสงคราม', district: 'สมุทรสาคร', branch: 'สมุทรสงคราม' },
  { region: 'ภาค 4', province: 'สมุทรสงคราม', district: 'สมุทรสาคร', branch: 'อัมพวา' },
  { region: 'ภาค 4', province: 'สมุทรสงคราม', district: 'สมุทรสาคร', branch: 'บางคนที' },
  { region: 'ภาค 4', province: 'สมุทรสงคราม', district: 'สมุทรสาคร', branch: 'เพชรสมุทร' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'กาญจนบุรี' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'ท่าม่วง' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'ท่าเรือ (กาญจนบุรี)' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'ท่ามะกา' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'พนมทวน' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'ลูกแก' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'ทองผาภูมิ' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'ลาดหญ้า' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'บ่อพลอย' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'ตลาดผาสุก' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'ห้วยกระเจา' },
  { region: 'ภาค 5', province: 'กาญจนบุรี', district: 'กาญจนบุรี', branch: 'ด่านมะขามเตี้ย' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'นครปฐม' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'บางเลน' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'กำแพงแสน' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'สนามจันทร์' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'ดอนตูม' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'เซ็นทรัล นครปฐม ' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'สามพราน' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'อ้อมใหญ่' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'นครชัยศรี' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'ศาลายา' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'บิ๊กซี อ้อมใหญ่' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'พุทธมณฑลสาย 4' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'ดอนหวาย' },
  { region: 'ภาค 5', province: 'นครปฐม', district: 'นครปฐม ', branch: 'เซ็นทรัล ศาลายา' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 1', branch: 'ติวานนท์' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 1', branch: 'นนทบุรี' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 1', branch: 'ปากเกร็ด' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 1', branch: 'แคราย' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 1', branch: 'เดอะมอลล์ งามวงศ์วาน' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 1', branch: 'เซ็นทรัล แจ้งวัฒนะ' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 1', branch: 'เซ็นทรัล รัตนาธิเบศร์ ' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 1', branch: 'ท่าน้ำนนทบุรี' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 1', branch: 'เมืองทองธานี' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 1', branch: 'ตลาดรวมใจ (เมืองทองธานี)' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 1', branch: 'สัมมากร เพลส ราชพฤกษ์' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 2', branch: 'บางบัวทอง' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 2', branch: 'บางกรวย' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 2', branch: 'บางใหญ่' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 2', branch: 'ไทรใหญ่' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 2', branch: 'อินเด็กซ์ บางใหญ่' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 2', branch: 'การไฟฟ้าฝ่ายผลิตบางกรวย' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 2', branch: 'บัวทองสแควร์' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 2', branch: 'ไทรน้อย' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 2', branch: 'เซ็นทรัล เวสต์เกต' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 2', branch: 'เซ็นทรัล เวสต์วิลล์ ' },
  { region: 'ภาค 5', province: 'นนทบุรี', district: 'นนทบุรี 2', branch: 'ตลาดเจ้าพระยา' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'สุพรรณบุรี' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'สองพี่น้อง' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'สามชุก' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'ศรีประจันต์' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'เดิมบางนางบวช' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'บางปลาม้า' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'อู่ทอง' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'ด่านช้าง' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'ดอนเจดีย์' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'หนองหญ้าไซ' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'ถนนนางพิม' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'โรบินสัน สุพรรณบุรี' },
  { region: 'ภาค 5', province: 'สุพรรณบุรี', district: 'สุพรรณบุรี', branch: 'ทุ่งคอก' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'นครสวรรค์' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'พยุหะคีรี' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'บรรพตพิสัย' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'ลาดยาว' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'สวรรค์วิถี' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'โกรกพระ' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'เซ็นทรัล นครสวรรค์ ' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'หนองปลิง' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'หนองเบน' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'ชุมตาบง' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'บิ๊กซี (วี - สแควร์) นครสวรรค์' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'ชุมแสง' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'ตาคลี' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'ท่าตะโก' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'ตากฟ้า' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'หนองบัว' },
  { region: 'ภาค 6', province: 'นครสวรรค์', district: 'นครสวรรค์ ', branch: 'ไพศาลี' },
  { region: 'ภาค 6', province: 'พิจิตร', district: 'พิจิตร', branch: 'พิจิตร' },
  { region: 'ภาค 6', province: 'พิจิตร', district: 'พิจิตร', branch: 'ตะพานหิน' },
  { region: 'ภาค 6', province: 'พิจิตร', district: 'พิจิตร', branch: 'บางมูลนาก' },
  { region: 'ภาค 6', province: 'พิจิตร', district: 'พิจิตร', branch: 'สามง่าม' },
  { region: 'ภาค 6', province: 'พิจิตร', district: 'พิจิตร', branch: 'ราชรถ' },
  { region: 'ภาค 6', province: 'พิจิตร', district: 'พิจิตร', branch: 'สากเหล็ก' },
  { region: 'ภาค 6', province: 'พิจิตร', district: 'พิจิตร', branch: 'โพทะเล' },
  { region: 'ภาค 6', province: 'พิจิตร', district: 'พิจิตร', branch: 'ทับคล้อ' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'เพชรบูรณ์' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'หล่มสัก' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'หนองไผ่' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'ซับสมอทอด' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'หล่มเก่า' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'วิเชียรบุรี' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'ชนแดน' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'ศรีเทพ' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'โลตัส เพชรบูรณ์' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'ตลาดท่าพล' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'บิ๊กซี หล่มสัก' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'วังโป่ง' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'ตลาดพุเตย' },
  { region: 'ภาค 6', province: 'เพชรบูรณ์', district: 'เพชรบูรณ์', branch: 'เขาค้อ' },
  { region: 'ภาค 6', province: 'ลพบุรี', district: 'ลพบุรี', branch: 'ลพบุรี' },
  { region: 'ภาค 6', province: 'ลพบุรี', district: 'ลพบุรี', branch: 'โคกกะเทียม' },
  { region: 'ภาค 6', province: 'ลพบุรี', district: 'ลพบุรี', branch: 'โคกสำโรง' },
  { region: 'ภาค 6', province: 'ลพบุรี', district: 'ลพบุรี', branch: 'บ้านหมี่' },
  { region: 'ภาค 6', province: 'ลพบุรี', district: 'ลพบุรี', branch: 'พัฒนานิคม' },
  { region: 'ภาค 6', province: 'ลพบุรี', district: 'ลพบุรี', branch: 'ลำนารายณ์' },
  { region: 'ภาค 6', province: 'ลพบุรี', district: 'ลพบุรี', branch: 'วงเวียนสระแก้ว' },
  { region: 'ภาค 6', province: 'ลพบุรี', district: 'ลพบุรี', branch: 'ท่าวุ้ง' },
  { region: 'ภาค 6', province: 'ลพบุรี', district: 'ลพบุรี', branch: 'หนองม่วง' },
  { region: 'ภาค 6', province: 'ลพบุรี', district: 'ลพบุรี', branch: 'โรบินสัน ลพบุรี' },
  { region: 'ภาค 6', province: 'ลพบุรี', district: 'ลพบุรี', branch: 'บิ๊กซี ลพบุรี 1' },
  { region: 'ภาค 6', province: 'ชัยนาท', district: 'อุทัยธานี', branch: 'ชัยนาท' },
  { region: 'ภาค 6', province: 'ชัยนาท', district: 'อุทัยธานี', branch: 'มโนรมย์' },
  { region: 'ภาค 6', province: 'ชัยนาท', district: 'อุทัยธานี', branch: 'วัดสิงห์' },
  { region: 'ภาค 6', province: 'ชัยนาท', district: 'อุทัยธานี', branch: 'หันคา' },
  { region: 'ภาค 6', province: 'ชัยนาท', district: 'อุทัยธานี', branch: 'สรรคบุรี' },
  { region: 'ภาค 6', province: 'ชัยนาท', district: 'อุทัยธานี', branch: 'สรรพยา' },
  { region: 'ภาค 6', province: 'ชัยนาท', district: 'อุทัยธานี', branch: 'สะพานใหม่ ชัยนาท' },
  { region: 'ภาค 6', province: 'อุทัยธานี', district: 'อุทัยธานี', branch: 'อุทัยธานี' },
  { region: 'ภาค 6', province: 'อุทัยธานี', district: 'อุทัยธานี', branch: 'หนองฉาง' },
  { region: 'ภาค 6', province: 'อุทัยธานี', district: 'อุทัยธานี', branch: 'ลานสัก' },
  { region: 'ภาค 6', province: 'อุทัยธานี', district: 'อุทัยธานี', branch: 'บ้านไร่' },
  { region: 'ภาค 7', province: 'กำแพงเพชร', district: 'กำแพงเพชร', branch: 'กำแพงเพชร' },
  { region: 'ภาค 7', province: 'กำแพงเพชร', district: 'กำแพงเพชร', branch: 'พรานกระต่าย' },
  { region: 'ภาค 7', province: 'กำแพงเพชร', district: 'กำแพงเพชร', branch: 'สลกบาตร' },
  { region: 'ภาค 7', province: 'กำแพงเพชร', district: 'กำแพงเพชร', branch: 'คลองขลุง' },
  { region: 'ภาค 7', province: 'กำแพงเพชร', district: 'กำแพงเพชร', branch: 'นครชุม' },
  { region: 'ภาค 7', province: 'กำแพงเพชร', district: 'กำแพงเพชร', branch: 'บิ๊กซี กำแพงเพชร' },
  { region: 'ภาค 7', province: 'กำแพงเพชร', district: 'กำแพงเพชร', branch: 'ลานกระบือ' },
  { region: 'ภาค 7', province: 'กำแพงเพชร', district: 'กำแพงเพชร', branch: 'ขาณุวรลักษบุรี' },
  { region: 'ภาค 7', province: 'กำแพงเพชร', district: 'กำแพงเพชร', branch: 'คลองลาน' },
  { region: 'ภาค 7', province: 'ตาก', district: 'ตาก', branch: 'ตาก' },
  { region: 'ภาค 7', province: 'ตาก', district: 'ตาก', branch: 'แม่สอด' },
  { region: 'ภาค 7', province: 'ตาก', district: 'ตาก', branch: 'แม่ระมาด' },
  { region: 'ภาค 7', province: 'ตาก', district: 'ตาก', branch: 'พบพระ' },
  { region: 'ภาค 7', province: 'ตาก', district: 'ตาก', branch: 'อุ้มผาง' },
  { region: 'ภาค 7', province: 'ตาก', district: 'ตาก', branch: 'บ้านตาก' },
  { region: 'ภาค 7', province: 'ตาก', district: 'ตาก', branch: 'บิ๊กซี ตาก' },
  { region: 'ภาค 7', province: 'ตาก', district: 'ตาก', branch: 'ตลาดพาเจริญ' },
  { region: 'ภาค 7', province: 'ตาก', district: 'ตาก', branch: 'ท่าสองยาง' },
  { region: 'ภาค 7', province: 'ตาก', district: 'ตาก', branch: 'โรบินสัน แม่สอด' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 1', branch: 'พิษณุโลก' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 1', branch: 'นางพญา' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 1', branch: 'มิตรภาพ' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 1', branch: 'บางระกำ' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 1', branch: 'ท่ามะปราง' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 1', branch: 'บิ๊กซี พิษณุโลก' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 1', branch: 'ห้าแยกโคกมะตูม' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 1', branch: 'เซ็นทรัล พิษณุโลก' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 1', branch: 'โลตัส พิษณุโลก ท่าทอง' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 2', branch: 'บางกระทุ่ม' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 2', branch: 'พรหมพิราม' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 2', branch: 'วังทอง' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 2', branch: 'นครไทย' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 2', branch: 'ชาติตระการ' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 2', branch: 'วัดโบสถ์' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 2', branch: 'ทรัพย์ไพรวัลย์' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 2', branch: 'หนองตม' },
  { region: 'ภาค 7', province: 'พิษณุโลก', district: 'พิษณุโลก 2', branch: 'เนินมะปราง' },
  { region: 'ภาค 7', province: 'สุโขทัย', district: 'สุโขทัย', branch: 'สุโขทัย' },
  { region: 'ภาค 7', province: 'สุโขทัย', district: 'สุโขทัย', branch: 'สวรรคโลก' },
  { region: 'ภาค 7', province: 'สุโขทัย', district: 'สุโขทัย', branch: 'ศรีสำโรง' },
  { region: 'ภาค 7', province: 'สุโขทัย', district: 'สุโขทัย', branch: 'ศรีสัชนาลัย' },
  { region: 'ภาค 7', province: 'สุโขทัย', district: 'สุโขทัย', branch: 'ทุ่งเสลี่ยม' },
  { region: 'ภาค 7', province: 'สุโขทัย', district: 'สุโขทัย', branch: 'กงไกรลาศ' },
  { region: 'ภาค 7', province: 'สุโขทัย', district: 'สุโขทัย', branch: 'คีรีมาศ' },
  { region: 'ภาค 7', province: 'สุโขทัย', district: 'สุโขทัย', branch: 'บ้านด่านลานหอย' },
  { region: 'ภาค 7', province: 'สุโขทัย', district: 'สุโขทัย', branch: 'ศรีนคร' },
  { region: 'ภาค 7', province: 'สุโขทัย', district: 'สุโขทัย', branch: 'บิ๊กซี สุโขทัย' },
  { region: 'ภาค 7', province: 'อุตรดิตถ์', district: 'อุตรดิตถ์', branch: 'อุตรดิตถ์' },
  { region: 'ภาค 7', province: 'อุตรดิตถ์', district: 'อุตรดิตถ์', branch: 'พิชัย' },
  { region: 'ภาค 7', province: 'อุตรดิตถ์', district: 'อุตรดิตถ์', branch: 'ลับแล' },
  { region: 'ภาค 7', province: 'อุตรดิตถ์', district: 'อุตรดิตถ์', branch: 'ตรอน' },
  { region: 'ภาค 7', province: 'อุตรดิตถ์', district: 'อุตรดิตถ์', branch: 'คลองโพ' },
  { region: 'ภาค 7', province: 'อุตรดิตถ์', district: 'อุตรดิตถ์', branch: 'น้ำปาด' },
  { region: 'ภาค 7', province: 'อุตรดิตถ์', district: 'อุตรดิตถ์', branch: 'มุขศาลา' },
  { region: 'ภาค 7', province: 'อุตรดิตถ์', district: 'อุตรดิตถ์', branch: 'ท่าปลา' },
  { region: 'ภาค 7', province: 'อุตรดิตถ์', district: 'อุตรดิตถ์', branch: 'ทองแสนขัน' },
  { region: 'ภาค 7', province: 'อุตรดิตถ์', district: 'อุตรดิตถ์', branch: 'ฟากท่า' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'เชียงใหม่' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'ประตูช้างเผือก' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'ท่าแพ' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'หนองหอย' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'ถนนทิพย์เนตร' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'เซ็นทรัล เชียงใหม่ แอร์พอร์ต ' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'ช้างคลาน' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'บิ๊กซี เชียงใหม่ (ดอนจั่น)' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'เซ็นทรัล เชียงใหม่' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'โลตัส คำเที่ยง' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'เม - ญ่า เชียงใหม่' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'ถนนห้วยแก้ว (เม - ญ่า เชียงใหม่)' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 1', branch: 'สามแยกสันทราย' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'มหาวิทยาลัยเชียงใหม่' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'สันทราย' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'ดอยสะเก็ด' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'ฝาง' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'แม่ริม' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'แม่แตง' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'เชียงดาว' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'ไชยปราการ' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'พร้าว' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'แม่อาย' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'เวียงแหง' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'แม่โจ้' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'มีโชคพลาซ่า' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'สันป่าตอง' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'สารภี' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'จอมทอง' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'หางดง' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'ฮอด' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'อมก๋อย' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'ดอยเต่า' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'บิ๊กซี หางดง ' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'แม่แจ่ม' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'แม่วาง' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'สันกำแพง' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'บวกครกหลวง' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 3', branch: 'บ่อสร้าง' },
  { region: 'ภาค 8', province: 'ลำพูน', district: 'ลำพูน', branch: 'ลำพูน' },
  { region: 'ภาค 8', province: 'ลำพูน', district: 'ลำพูน', branch: 'ป่าซาง' },
  { region: 'ภาค 8', province: 'ลำพูน', district: 'ลำพูน', branch: 'ลี้' },
  { region: 'ภาค 8', province: 'ลำพูน', district: 'ลำพูน', branch: 'นิคมอุตสาหกรรมลำพูน' },
  { region: 'ภาค 8', province: 'ลำพูน', district: 'ลำพูน', branch: 'บ้านโฮ่ง' },
  { region: 'ภาค 8', province: 'แม่ฮ่องสอน', district: 'ลำพูน', branch: 'แม่สะเรียง' },
  { region: 'ภาค 8', province: 'แม่ฮ่องสอน', district: 'ลำพูน', branch: 'แม่ฮ่องสอน' },
  { region: 'ภาค 8', province: 'แม่ฮ่องสอน', district: 'ลำพูน', branch: 'ปาย' },
  { region: 'ภาค 8', province: 'แม่ฮ่องสอน', district: 'ลำพูน', branch: 'แม่ลาน้อย' },
  { region: 'ภาค 8', province: 'แม่ฮ่องสอน', district: 'ลำพูน', branch: 'ขุนยวม' },
  { region: 'ภาค 8', province: 'ลำพูน', district: 'ลำพูน', branch: 'กาดลำพูนจตุจักร' },
  { region: 'ภาค 8', province: 'ลำพูน', district: 'ลำพูน', branch: 'บิ๊กซี ลำพูน' },
  { region: 'ภาค 8', province: 'เชียงใหม่', district: 'เชียงใหม่ 2', branch: 'สะเมิง ' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'เชียงราย' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'พาน' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'แม่จัน' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'แม่สาย' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'เชียงของ' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'เวียงป่าเป้า' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'เทิง' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'เชียงแสน' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'กลางเวียง' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'มหาวิทยาลัยแม่ฟ้าหลวง' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'เซ็นทรัล เชียงราย' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'เวียงเชียงรุ้ง' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'แม่สรวย' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'บ้านดู่' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'ขุนตาล' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'แม่ขะจาน' },
  { region: 'ภาค 9', province: 'เชียงราย', district: 'เชียงราย', branch: 'ร่องขุ่น' },
  { region: 'ภาค 9', province: 'น่าน', district: 'น่าน', branch: 'น่าน' },
  { region: 'ภาค 9', province: 'น่าน', district: 'น่าน', branch: 'เวียงสา' },
  { region: 'ภาค 9', province: 'น่าน', district: 'น่าน', branch: 'ปัว' },
  { region: 'ภาค 9', province: 'น่าน', district: 'น่าน', branch: 'นาน้อย' },
  { region: 'ภาค 9', province: 'น่าน', district: 'น่าน', branch: 'ท่าวังผา' },
  { region: 'ภาค 9', province: 'น่าน', district: 'น่าน', branch: 'แม่จริม' },
  { region: 'ภาค 9', province: 'น่าน', district: 'น่าน', branch: 'ห้างนราไฮเปอร์มาร์ท' },
  { region: 'ภาค 9', province: 'น่าน', district: 'น่าน', branch: 'เชียงกลาง' },
  { region: 'ภาค 9', province: 'น่าน', district: 'น่าน', branch: 'ทุ่งช้าง' },
  { region: 'ภาค 9', province: 'น่าน', district: 'น่าน', branch: 'สองแคว' },
  { region: 'ภาค 9', province: 'น่าน', district: 'น่าน', branch: 'เฉลิมพระเกียรติ' },
  { region: 'ภาค 9', province: 'พะเยา', district: 'พะเยา', branch: 'พะเยา' },
  { region: 'ภาค 9', province: 'พะเยา', district: 'พะเยา', branch: 'เชียงคำ' },
  { region: 'ภาค 9', province: 'พะเยา', district: 'พะเยา', branch: 'จุน' },
  { region: 'ภาค 9', province: 'พะเยา', district: 'พะเยา', branch: 'ปง' },
  { region: 'ภาค 9', province: 'พะเยา', district: 'พะเยา', branch: 'ดอกคำใต้' },
  { region: 'ภาค 9', province: 'พะเยา', district: 'พะเยา', branch: 'มหาวิทยาลัยพะเยา' },
  { region: 'ภาค 9', province: 'พะเยา', district: 'พะเยา', branch: 'แม่ใจ' },
  { region: 'ภาค 9', province: 'พะเยา', district: 'พะเยา', branch: 'ท็อปส์ พลาซ่า พะเยา' },
  { region: 'ภาค 9', province: 'แพร่', district: 'แพร่', branch: 'แพร่' },
  { region: 'ภาค 9', province: 'แพร่', district: 'แพร่', branch: 'เด่นชัย' },
  { region: 'ภาค 9', province: 'แพร่', district: 'แพร่', branch: 'สอง' },
  { region: 'ภาค 9', province: 'แพร่', district: 'แพร่', branch: 'ร้องกวาง' },
  { region: 'ภาค 9', province: 'แพร่', district: 'แพร่', branch: 'สูงเม่น' },
  { region: 'ภาค 9', province: 'แพร่', district: 'แพร่', branch: 'กาดน้ำทอง แพร่' },
  { region: 'ภาค 9', province: 'แพร่', district: 'แพร่', branch: 'ลอง' },
  { region: 'ภาค 9', province: 'แพร่', district: 'แพร่', branch: 'ทุ่งโฮ้ง' },
  { region: 'ภาค 9', province: 'แพร่', district: 'แพร่', branch: 'วังชิ้น' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'ลำปาง' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'สบตุ๋ย' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'แจ้ห่ม' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'วังเหนือ' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'บิ๊กซี ลำปาง' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'เซ็นทรัล ลำปาง' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'น้ำโท้ง' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'เกาะคา' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'งาว' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'เถิน' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'ห้างฉัตร' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'แม่ทะ' },
  { region: 'ภาค 9', province: 'ลำปาง', district: 'ลำปาง ', branch: 'แม่เมาะ' },
  { region: 'ภาค 10', province: 'นครพนม', district: 'นครพนม', branch: 'นครพนม' },
  { region: 'ภาค 10', province: 'นครพนม', district: 'นครพนม', branch: 'ธาตุพนม' },
  { region: 'ภาค 10', province: 'นครพนม', district: 'นครพนม', branch: 'ท่าอุเทน' },
  { region: 'ภาค 10', province: 'นครพนม', district: 'นครพนม', branch: 'นาแก' },
  { region: 'ภาค 10', province: 'นครพนม', district: 'นครพนม', branch: 'บ้านแพง' },
  { region: 'ภาค 10', province: 'นครพนม', district: 'นครพนม', branch: 'ศรีสงคราม' },
  { region: 'ภาค 10', province: 'นครพนม', district: 'นครพนม', branch: 'เรณูนคร' },
  { region: 'ภาค 10', province: 'นครพนม', district: 'นครพนม', branch: 'นาหว้า' },
  { region: 'ภาค 10', province: 'นครพนม', district: 'นครพนม', branch: 'โพนสวรรค์' },
  { region: 'ภาค 10', province: 'นครพนม', district: 'นครพนม', branch: 'ปลาปาก' },
  { region: 'ภาค 10', province: 'เลย ', district: 'เลย', branch: 'เลย' },
  { region: 'ภาค 10', province: 'เลย ', district: 'เลย', branch: 'เชียงคาน' },
  { region: 'ภาค 10', province: 'เลย ', district: 'เลย', branch: 'ปากชม' },
  { region: 'ภาค 10', province: 'เลย ', district: 'เลย', branch: 'ด่านซ้าย' },
  { region: 'ภาค 10', province: 'เลย ', district: 'เลย', branch: 'ภูกระดึง' },
  { region: 'ภาค 10', province: 'เลย ', district: 'เลย', branch: 'ภูเรือ' },
  { region: 'ภาค 10', province: 'เลย ', district: 'เลย', branch: 'ท่าลี่' },
  { region: 'ภาค 10', province: 'เลย ', district: 'เลย', branch: 'นาอาน' },
  { region: 'ภาค 10', province: 'เลย ', district: 'เลย', branch: 'วังสะพุง' },
  { region: 'ภาค 10', province: 'หนองบัวลำภู', district: 'หนองบัวลำภู', branch: 'หนองบัวลำภู' },
  { region: 'ภาค 10', province: 'หนองบัวลำภู', district: 'หนองบัวลำภู', branch: 'ศรีบุญเรือง' },
  { region: 'ภาค 10', province: 'หนองบัวลำภู', district: 'หนองบัวลำภู', branch: 'โนนสัง' },
  { region: 'ภาค 10', province: 'หนองบัวลำภู', district: 'หนองบัวลำภู', branch: 'นากลาง' },
  { region: 'ภาค 10', province: 'หนองบัวลำภู', district: 'หนองบัวลำภู', branch: 'สุวรรณคูหา' },
  { region: 'ภาค 10', province: 'หนองบัวลำภู', district: 'หนองบัวลำภู', branch: 'นาวัง' },
  { region: 'ภาค 10', province: 'สกลนคร', district: 'สกลนคร', branch: 'สกลนคร' },
  { region: 'ภาค 10', province: 'สกลนคร', district: 'สกลนคร', branch: 'สว่างแดนดิน' },
  { region: 'ภาค 10', province: 'สกลนคร', district: 'สกลนคร', branch: 'วานรนิวาส' },
  { region: 'ภาค 10', province: 'สกลนคร', district: 'สกลนคร', branch: 'พังโคน' },
  { region: 'ภาค 10', province: 'สกลนคร', district: 'สกลนคร', branch: 'ถนนประชาราษฎร์' },
  { region: 'ภาค 10', province: 'สกลนคร', district: 'สกลนคร', branch: 'กุสุมาลย์' },
  { region: 'ภาค 10', province: 'สกลนคร', district: 'สกลนคร', branch: 'บ้านม่วง' },
  { region: 'ภาค 10', province: 'สกลนคร', district: 'สกลนคร', branch: 'คำตากล้า' },
  { region: 'ภาค 10', province: 'สกลนคร', district: 'สกลนคร', branch: 'อากาศอำนวย' },
  { region: 'ภาค 10', province: 'สกลนคร', district: 'สกลนคร', branch: 'โรบินสัน สกลนคร' },
  { region: 'ภาค 10', province: 'หนองคาย', district: 'หนองคาย', branch: 'หนองคาย' },
  { region: 'ภาค 10', province: 'หนองคาย', district: 'หนองคาย', branch: 'ท่าบ่อ' },
  { region: 'ภาค 10', province: 'หนองคาย', district: 'หนองคาย', branch: 'โพนพิสัย' },
  { region: 'ภาค 10', province: 'หนองคาย', district: 'หนองคาย', branch: 'ศรีเชียงใหม่' },
  { region: 'ภาค 10', province: 'หนองคาย', district: 'หนองคาย', branch: 'อัศวรรณ ช้อปปิ้ง คอมเพล็กซ์ หนองคาย' },
  { region: 'ภาค 10', province: 'หนองคาย', district: 'หนองคาย', branch: 'สังคม' },
  { region: 'ภาค 10', province: 'บึงกาฬ', district: 'บึงกาฬ', branch: 'บึงกาฬ' },
  { region: 'ภาค 10', province: 'บึงกาฬ', district: 'บึงกาฬ', branch: 'พรเจริญ' },
  { region: 'ภาค 10', province: 'บึงกาฬ', district: 'บึงกาฬ', branch: 'ปากคาด' },
  { region: 'ภาค 10', province: 'บึงกาฬ', district: 'บึงกาฬ', branch: 'เซกา' },
  { region: 'ภาค 10', province: 'บึงกาฬ', district: 'บึงกาฬ', branch: 'โซ่พิสัย' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 1', branch: 'อุดรธานี' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 1', branch: 'บ้านผือ' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 1', branch: 'น้ำโสม' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 1', branch: 'ประชารักษา' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 1', branch: 'บงคำ' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 1', branch: 'โลตัส นาดี อุดรธานี' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 1', branch: 'ตลาดอุดรเมืองทองเจริญศรี' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 1', branch: 'กุดจับ' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 1', branch: 'เซ็นทรัล อุดรธานี' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 1', branch: 'ยูดี ทาวน์ อุดรธานี' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 2', branch: 'กุมภวาปี' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 2', branch: 'หนองหาน' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 2', branch: 'เพ็ญ' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 2', branch: 'บ้านดุง' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 2', branch: 'โนนสะอาด' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 2', branch: 'วังสามหมอ' },
  { region: 'ภาค 10', province: 'อุดรธานี', district: 'อุดรธานี 2', branch: 'ศรีธาตุ' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'กาฬสินธุ์' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'สมเด็จ' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'กมลาไสย' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'ถีนานนท์' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'ยางตลาด' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'โลตัส กาฬสินธุ์' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'คำม่วง' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'ท่าคันโท' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'เขาวง' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'หนองกุงศรี' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'สหัสขันธ์' },
  { region: 'ภาค 11', province: 'กาฬสินธุ์', district: 'กาฬสินธุ์', branch: 'กุฉินารายณ์' },
  { region: 'ภาค 11', province: 'มุกดาหาร', district: 'มุกดาหาร', branch: 'มุกดาหาร' },
  { region: 'ภาค 11', province: 'มุกดาหาร', district: 'มุกดาหาร', branch: 'ดอนตาล' },
  { region: 'ภาค 11', province: 'มุกดาหาร', district: 'มุกดาหาร', branch: 'คำชะอี' },
  { region: 'ภาค 11', province: 'มุกดาหาร', district: 'มุกดาหาร', branch: 'ตลาดพรเพชร' },
  { region: 'ภาค 11', province: 'มุกดาหาร', district: 'มุกดาหาร', branch: 'นิคมคำสร้อย' },
  { region: 'ภาค 11', province: 'มุกดาหาร', district: 'มุกดาหาร', branch: 'บิ๊กซี มุกดาหาร' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 1', branch: 'ขอนแก่น' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 1', branch: 'บ้านไผ่' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 1', branch: 'น้ำพอง' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 1', branch: 'มะลิวัลย์' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 1', branch: 'กระนวน' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 1', branch: 'ศรีจันทร์' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 1', branch: 'ศูนย์ราชการ' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 1', branch: 'อุบลรัตน์' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 1', branch: 'เซ็นทรัล ขอนแก่น' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 1', branch: 'ประตูน้ำขอนแก่น' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 1', branch: 'เขาสวนกวาง' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 2', branch: 'พล' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 2', branch: 'ชุมแพ' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 2', branch: 'มัญจาคีรี' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 2', branch: 'ภูเวียง' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 2', branch: 'ภูผาม่าน' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 2', branch: 'หนองสองห้อง' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 2', branch: 'สีชมพู' },
  { region: 'ภาค 11', province: 'ขอนแก่น', district: 'ขอนแก่น 2', branch: 'หนองเรือ' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'ชัยภูมิ' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'ภูเขียว' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'จัตุรัส' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'แก้งคร้อ' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'เกษตรสมบูรณ์' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'หนองบัวแดง' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'ห้าแยกโนนไฮ' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'คอนสวรรค์' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'หนองบัวระเหว' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'เทพสถิต' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'บำเหน็จณรงค์' },
  { region: 'ภาค 11', province: 'ชัยภูมิ', district: 'ชัยภูมิ', branch: 'บ้านเขว้า' },
  { region: 'ภาค 11', province: 'มหาสารคาม', district: 'มหาสารคาม', branch: 'มหาสารคาม' },
  { region: 'ภาค 11', province: 'มหาสารคาม', district: 'มหาสารคาม', branch: 'โกสุมพิสัย' },
  { region: 'ภาค 11', province: 'มหาสารคาม', district: 'มหาสารคาม', branch: 'บรบือ' },
  { region: 'ภาค 11', province: 'มหาสารคาม', district: 'มหาสารคาม', branch: 'วาปีปทุม' },
  { region: 'ภาค 11', province: 'มหาสารคาม', district: 'มหาสารคาม', branch: 'พยัคฆภูมิพิสัย' },
  { region: 'ภาค 11', province: 'มหาสารคาม', district: 'มหาสารคาม', branch: 'เชียงยืน' },
  { region: 'ภาค 11', province: 'มหาสารคาม', district: 'มหาสารคาม', branch: 'ท่าขอนยาง' },
  { region: 'ภาค 11', province: 'มหาสารคาม', district: 'มหาสารคาม', branch: 'นาเชือก' },
  { region: 'ภาค 11', province: 'มหาสารคาม', district: 'มหาสารคาม', branch: 'เสริมไทยคอมเพล็กซ์' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'ร้อยเอ็ด' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'สุวรรณภูมิ' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'โพนทอง' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'เกษตรวิสัย' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'เสลภูมิ' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'จตุรพักตรพิมาน' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'พนมไพร' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'อาจสามารถ' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'เทวาภิบาล' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'ปทุมรัตต์' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'โพธิ์ชัย' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'หนองพอก' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'สี่แยกโรงพยาบาลร้อยเอ็ด' },
  { region: 'ภาค 11', province: 'ร้อยเอ็ด', district: 'ร้อยเอ็ด', branch: 'โรบินสัน ร้อยเอ็ด' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'บุรีรัมย์' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'นางรอง' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'ลำปลายมาศ' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'ประโคนชัย' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'สตึก' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'พุทไธสง' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'กระสัง' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'หนองกี่' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'ทวีกิจ' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'บ้านกรวด' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'ละหานทราย' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'บ้านใหม่ไชยพจน์' },
  { region: 'ภาค 12', province: 'บุรีรัมย์', district: 'บุรีรัมย์', branch: 'โรบินสัน บุรีรัมย์' },
  { region: 'ภาค 12', province: 'ยโสธร', district: 'ยโสธร', branch: 'ยโสธร' },
  { region: 'ภาค 12', province: 'ยโสธร', district: 'ยโสธร', branch: 'เลิงนกทา' },
  { region: 'ภาค 12', province: 'ยโสธร', district: 'ยโสธร', branch: 'กุดชุม' },
  { region: 'ภาค 12', province: 'ยโสธร', district: 'ยโสธร', branch: 'คำเขื่อนแก้ว' },
  { region: 'ภาค 12', province: 'ยโสธร', district: 'ยโสธร', branch: 'มหาชนะชัย' },
  { region: 'ภาค 12', province: 'อำนาจเจริญ', district: 'ยโสธร', branch: 'อำนาจเจริญ' },
  { region: 'ภาค 12', province: 'อำนาจเจริญ', district: 'ยโสธร', branch: 'ปทุมราชวงศา' },
  { region: 'ภาค 12', province: 'อำนาจเจริญ', district: 'ยโสธร', branch: 'ลืออำนาจ' },
  { region: 'ภาค 12', province: 'ยโสธร', district: 'ยโสธร', branch: 'ถนนวิทยะธำรงค์' },
  { region: 'ภาค 12', province: 'ศรีสะเกษ', district: 'ศรีสะเกษ', branch: 'ศรีสะเกษ' },
  { region: 'ภาค 12', province: 'ศรีสะเกษ', district: 'ศรีสะเกษ', branch: 'กันทรลักษ์' },
  { region: 'ภาค 12', province: 'ศรีสะเกษ', district: 'ศรีสะเกษ', branch: 'ราษีไศล' },
  { region: 'ภาค 12', province: 'ศรีสะเกษ', district: 'ศรีสะเกษ', branch: 'กันทรารมย์' },
  { region: 'ภาค 12', province: 'ศรีสะเกษ', district: 'ศรีสะเกษ', branch: 'ขุนหาญ' },
  { region: 'ภาค 12', province: 'ศรีสะเกษ', district: 'ศรีสะเกษ', branch: 'ขุขันธ์' },
  { region: 'ภาค 12', province: 'ศรีสะเกษ', district: 'ศรีสะเกษ', branch: 'อุทุมพรพิสัย' },
  { region: 'ภาค 12', province: 'ศรีสะเกษ', district: 'ศรีสะเกษ', branch: 'ถนนเทพา' },
  { region: 'ภาค 12', province: 'สุรินทร์', district: 'สุรินทร์', branch: 'สุรินทร์' },
  { region: 'ภาค 12', province: 'สุรินทร์', district: 'สุรินทร์', branch: 'ศีขรภูมิ' },
  { region: 'ภาค 12', province: 'สุรินทร์', district: 'สุรินทร์', branch: 'ท่าตูม' },
  { region: 'ภาค 12', province: 'สุรินทร์', district: 'สุรินทร์', branch: 'รัตนบุรี' },
  { region: 'ภาค 12', province: 'สุรินทร์', district: 'สุรินทร์', branch: 'ปราสาท' },
  { region: 'ภาค 12', province: 'สุรินทร์', district: 'สุรินทร์', branch: 'สังขะ' },
  { region: 'ภาค 12', province: 'สุรินทร์', district: 'สุรินทร์', branch: 'แยกหนองบัว ' },
  { region: 'ภาค 12', province: 'สุรินทร์', district: 'สุรินทร์', branch: 'ชุมพลบุรี' },
  { region: 'ภาค 12', province: 'สุรินทร์', district: 'สุรินทร์', branch: 'โรบินสัน สุรินทร์' },
  { region: 'ภาค 12', province: 'สุรินทร์', district: 'สุรินทร์', branch: 'จอมพระ' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 1', branch: 'อุบลราชธานี' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 1', branch: 'เขมราฐ' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 1', branch: 'โพธิ์ไทร' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 1', branch: 'ตระการพืชผล' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 1', branch: 'ถนนยุทธภัณฑ์' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 1', branch: 'ศรีเมืองใหม่' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 1', branch: 'ม่วงสามสิบ' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 1', branch: 'ซิตี้มอลล์ อุบลราชธานี' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 1', branch: 'ถนนแจ้งสนิท' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 1', branch: 'เซ็นทรัล อุบลราชธานี' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 1', branch: 'กุดข้าวปุ้น' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 2', branch: 'พิบูลมังสาหาร' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 2', branch: 'วารินชำราบ' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 2', branch: 'เดชอุดม' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 2', branch: 'เขื่องใน' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 2', branch: 'นาจะหลวย' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 2', branch: 'น้ำยืน' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 2', branch: 'ถนนสถลมาร์ค' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 2', branch: 'โขงเจียม' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 2', branch: 'โนนผึ้ง' },
  { region: 'ภาค 12', province: 'อุบลราชธานี', district: 'อุบลราชธานี 2', branch: 'ถนนสถิตย์นิมานกาล' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'สุรนารี' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'โชคชัย' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'มุขมนตรี' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'ครบุรี' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'เดอะมอลล์ นครราชสีมา' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'โคกกรวด' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'เสิงสาง' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'หนองบุญมาก' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'ตลาดเซฟวัน' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'เซ็นทรัล โคราช' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'โนนสูง' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'โนนไทย' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'จักราช' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'นครราชสีมา' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'ถนนจอมพล' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'ประตูชุมพล' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'เทอมินอล21 โคราช' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'บัวใหญ่' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'พิมาย' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'คง' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'ชุมพวง' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 1', branch: 'ประทาย' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'แก้งสนามนาง' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'ห้วยแถลง' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 2', branch: 'บัวลาย' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 3', branch: 'สูงเนิน' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 3', branch: 'ปากช่อง' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 3', branch: 'ปักธงชัย' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 3', branch: 'สีคิ้ว' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 3', branch: 'ด่านขุนทด' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 3', branch: 'ธนะรัชต์ เขาใหญ่' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 3', branch: 'โลตัส ปากช่อง' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 3', branch: 'กลางดง' },
  { region: 'ภาค 13', province: 'นครราชสีมา', district: 'นครราชสีมา 3', branch: 'วังน้ำเขียว' },
  { region: 'ภาค 13', province: 'ปราจีนบุรี', district: 'ปราจีนบุรี', branch: 'ปราจีนบุรี' },
  { region: 'ภาค 13', province: 'ปราจีนบุรี', district: 'ปราจีนบุรี', branch: 'กบินทร์บุรี' },
  { region: 'ภาค 13', province: 'ปราจีนบุรี', district: 'ปราจีนบุรี', branch: 'ประจันตคาม' },
  { region: 'ภาค 13', province: 'ปราจีนบุรี', district: 'ปราจีนบุรี', branch: 'สี่แยกกบินทร์บุรี' },
  { region: 'ภาค 13', province: 'ปราจีนบุรี', district: 'ปราจีนบุรี', branch: 'ศรีมหาโพธิ' },
  { region: 'ภาค 13', province: 'ปราจีนบุรี', district: 'ปราจีนบุรี', branch: 'นิคมอุตสาหกรรม 304' },
  { region: 'ภาค 13', province: 'ปราจีนบุรี', district: 'ปราจีนบุรี', branch: 'โคกอุดม' },
  { region: 'ภาค 13', province: 'ปราจีนบุรี', district: 'ปราจีนบุรี', branch: 'โรบินสัน ปราจีนบุรี' },
  { region: 'ภาค 13', province: 'นครนายก', district: 'ปราจีนบุรี', branch: 'นครนายก' },
  { region: 'ภาค 13', province: 'นครนายก', district: 'ปราจีนบุรี', branch: 'บ้านนา' },
  { region: 'ภาค 13', province: 'นครนายก', district: 'ปราจีนบุรี', branch: 'องครักษ์' },
  { region: 'ภาค 13', province: 'สระแก้ว', district: 'สระแก้ว', branch: 'สระแก้ว' },
  { region: 'ภาค 13', province: 'สระแก้ว', district: 'สระแก้ว', branch: 'อรัญประเทศ' },
  { region: 'ภาค 13', province: 'สระแก้ว', district: 'สระแก้ว', branch: 'วังน้ำเย็น' },
  { region: 'ภาค 13', province: 'สระแก้ว', district: 'สระแก้ว', branch: 'วัฒนานคร' },
  { region: 'ภาค 13', province: 'สระแก้ว', district: 'สระแก้ว', branch: 'ตลาดโรงเกลือ' },
  { region: 'ภาค 13', province: 'สระแก้ว', district: 'สระแก้ว', branch: 'วังสมบูรณ์' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 1', branch: 'ปทุมธานี' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 1', branch: 'รังสิต' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 1', branch: 'ลาดหลุมแก้ว' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 1', branch: 'นวนคร' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 1', branch: 'หมู่บ้านเมืองเอก' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 1', branch: 'ทียูโดม รังสิต' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 1', branch: 'ตลาดพูนทรัพย์' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 1', branch: 'สามโคก' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 1', branch: 'ตลาดไท' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 2', branch: 'ลำลูกกา' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 2', branch: 'คลองหลวง' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 2', branch: 'คลอง 10 ธัญบุรี' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 2', branch: 'เมเจอร์ รังสิต' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 2', branch: 'สัมมากร เพลส รังสิต คลอง 2' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 2', branch: 'ฟิวเจอร์พาร์ค รังสิต' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 2', branch: 'ลำไทร' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 2', branch: 'โลตัส รังสิตคลอง 7' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 2', branch: 'บิ๊กซี ลำลูกกา 2' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 2', branch: 'บิ๊กซี ลำลูกกา 1' },
  { region: 'ภาค 14', province: 'ปทุมธานี', district: 'ปทุมธานี 2', branch: 'ฟิวเจอร์พาร์ค  (ฟิวเจอร์พาร์ค รังสิต)' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 1', branch: 'ท่าเรือ (อยุธยา)' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 1', branch: 'ภาชี' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 1', branch: 'อุทัย' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 1', branch: 'บางปะอิน' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 1', branch: 'นครหลวง' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 1', branch: 'วังน้อย' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 1', branch: 'ประตูน้ำพระอินทร์' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 1', branch: 'คลองสวนพลู' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 1', branch: 'อยุธยาพาร์ค' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 1', branch: 'นิคมอุตสาหกรรมบางปะอิน' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 2', branch: 'พระนครศรีอยุธยา' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 2', branch: 'เสนา' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 2', branch: 'ผักไห่' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 2', branch: 'บ้านแพรก' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 2', branch: 'มหาราช' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 2', branch: 'บางปะหัน' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 2', branch: 'ลาดบัวหลวง' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 2', branch: 'เจ้าพรหม' },
  { region: 'ภาค 14', province: 'พระนครศรีอยุธยา ', district: 'พระนครศรีอยุธยา 2', branch: 'สวนอุตสาหกรรมโรจนะ' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'สระบุรี' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'พระพุทธบาท' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'แก่งคอย' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'หนองแค' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'บ้านหมอ' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'มวกเหล็ก' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'วิหารแดง' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'เสาไห้' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'สุขอนันต์ปาร์ค' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'วังม่วง' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'หินกอง' },
  { region: 'ภาค 14', province: 'สระบุรี', district: 'สระบุรี', branch: 'โรบินสัน สระบุรี' },
  { region: 'ภาค 14', province: 'อ่างทอง', district: 'อ่างทอง', branch: 'อ่างทอง' },
  { region: 'ภาค 14', province: 'อ่างทอง', district: 'อ่างทอง', branch: 'วิเศษชัยชาญ' },
  { region: 'ภาค 14', province: 'อ่างทอง', district: 'อ่างทอง', branch: 'โพธิ์ทอง' },
  { region: 'ภาค 14', province: 'อ่างทอง', district: 'อ่างทอง', branch: 'ป่าโมก' },
  { region: 'ภาค 14', province: 'สิงห์บุรี', district: 'อ่างทอง', branch: 'สิงห์บุรี' },
  { region: 'ภาค 14', province: 'สิงห์บุรี', district: 'อ่างทอง', branch: 'อินทร์บุรี' },
  { region: 'ภาค 14', province: 'สิงห์บุรี', district: 'อ่างทอง', branch: 'บางระจัน' },
  { region: 'ภาค 14', province: 'สิงห์บุรี', district: 'อ่างทอง', branch: 'ท่าช้าง' },
  { region: 'ภาค 14', province: 'สิงห์บุรี', district: 'อ่างทอง', branch: 'ท็อปส์ พลาซ่า สิงห์บุรี' },
  { region: 'ภาค 15', province: 'จันทบุรี', district: 'จันทบุรี', branch: 'เขาคิชฌกูฏ' },
  { region: 'ภาค 15', province: 'ตราด', district: 'จันทบุรี', branch: 'เกาะช้าง ' },
  { region: 'ภาค 15', province: 'ตราด', district: 'จันทบุรี', branch: 'คลองใหญ่' },
  { region: 'ภาค 15', province: 'ตราด', district: 'จันทบุรี', branch: 'ชัยมงคล - ตราด' },
  { region: 'ภาค 15', province: 'ตราด', district: 'จันทบุรี', branch: 'เกาะกูด (ชัยมงคล-ตราด)' },
  { region: 'ภาค 15', province: 'จันทบุรี', district: 'จันทบุรี', branch: 'เรนโบว์ พลาซา จันทบุรี' },
  { region: 'ภาค 15', province: 'จันทบุรี', district: 'จันทบุรี', branch: 'จันทบุรี' },
  { region: 'ภาค 15', province: 'จันทบุรี', district: 'จันทบุรี', branch: 'ท่าใหม่' },
  { region: 'ภาค 15', province: 'จันทบุรี', district: 'จันทบุรี', branch: 'ถนนท่าแฉลบ' },
  { region: 'ภาค 15', province: 'ตราด', district: 'จันทบุรี', branch: 'ตราด' },
  { region: 'ภาค 15', province: 'จันทบุรี', district: 'จันทบุรี', branch: 'ขลุง' },
  { region: 'ภาค 15', province: 'จันทบุรี', district: 'จันทบุรี', branch: 'สอยดาว' },
  { region: 'ภาค 15', province: 'จันทบุรี', district: 'จันทบุรี', branch: 'ห้วยสะท้อน' },
  { region: 'ภาค 15', province: 'จันทบุรี', district: 'จันทบุรี', branch: 'ตลาดเทศบาล 2' },
  { region: 'ภาค 15', province: 'ตราด', district: 'จันทบุรี', branch: 'เขาสมิง' },
  { region: 'ภาค 15', province: 'ฉะเชิงเทรา', district: 'ฉะเชิงเทรา', branch: 'บางน้ำเปรี้ยว' },
  { region: 'ภาค 15', province: 'ฉะเชิงเทรา', district: 'ฉะเชิงเทรา', branch: 'สนามชัยเขต' },
  { region: 'ภาค 15', province: 'ฉะเชิงเทรา', district: 'ฉะเชิงเทรา', branch: 'ฉะเชิงเทรา' },
  { region: 'ภาค 15', province: 'ฉะเชิงเทรา', district: 'ฉะเชิงเทรา', branch: 'บางปะกง' },
  { region: 'ภาค 15', province: 'ฉะเชิงเทรา', district: 'ฉะเชิงเทรา', branch: 'พนมสารคาม' },
  { region: 'ภาค 15', province: 'ฉะเชิงเทรา', district: 'ฉะเชิงเทรา', branch: 'บางคล้า' },
  { region: 'ภาค 15', province: 'ฉะเชิงเทรา', district: 'ฉะเชิงเทรา', branch: 'ถนนมหาจักรพรรดิ์' },
  { region: 'ภาค 15', province: 'ฉะเชิงเทรา', district: 'ฉะเชิงเทรา', branch: 'โรบินสัน ฉะเชิงเทรา' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 1', branch: 'ศรีราชา' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 1', branch: 'ถนนพระยาสัจจา' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 1', branch: 'บางทราย' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 1', branch: 'ชลบุรี' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 1', branch: 'หนองมน' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 1', branch: 'ถนนสุขประยูร' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 1', branch: 'แปซิฟิค พาร์ค ศรีราชา' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 1', branch: 'เซ็นทรัล ชลบุรี' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 1', branch: 'ฮาร์เบอร์ มอลล์ แหลมฉบัง' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 1', branch: 'Exim Bank แหลมฉบัง (ศรีราชา)' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 2', branch: 'ถนนทัพพระยา' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 2', branch: 'บางละมุง' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 2', branch: 'เมืองพัทยา' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 2', branch: 'พัทยาใต้' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 2', branch: 'โพธิสัมพันธ์' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 2', branch: 'เซ็นทรัล พัทยา' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 2', branch: 'บิ๊กซี พัทยาใต้' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 3', branch: 'เกาะโพธิ์' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 3', branch: 'นิคมอุตสาหกรรมอมตะนคร' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 3', branch: 'พนัสนิคม' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 3', branch: 'บ้านบึง' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 3', branch: 'พานทอง' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 3', branch: 'หัวกุญแจ' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 3', branch: 'ดอนหัวฬ่อ' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 4', branch: 'เนินพลับหวาน' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 4', branch: 'บุญสัมพันธ์' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 4', branch: 'สุขุมวิท - สัตหีบ' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 4', branch: 'สยามคันทรีคลับ' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 4', branch: 'สัตหีบ' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 4', branch: 'สวนอุตสาหกรรมศรีราชา' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 4', branch: 'ตลาดบ้านอำเภอ' },
  { region: 'ภาค 15', province: 'ชลบุรี', district: 'ชลบุรี 4', branch: 'บ่อวิน' },
  { region: 'ภาค 15', province: 'ระยอง', district: 'ระยอง', branch: 'ระยอง' },
  { region: 'ภาค 15', province: 'ระยอง', district: 'ระยอง', branch: 'มาบตาพุด' },
  { region: 'ภาค 15', province: 'ระยอง', district: 'ระยอง', branch: 'เนินพระ' },
  { region: 'ภาค 15', province: 'ระยอง', district: 'ระยอง', branch: 'บ้านค่าย' },
  { region: 'ภาค 15', province: 'ระยอง', district: 'ระยอง', branch: 'แกลง' },
  { region: 'ภาค 15', province: 'ระยอง', district: 'ระยอง', branch: 'บ้านฉาง' },
  { region: 'ภาค 15', province: 'ระยอง', district: 'ระยอง', branch: 'เพ' },
  { region: 'ภาค 15', province: 'ระยอง', district: 'ระยอง', branch: 'ปลวกแดง' },
  { region: 'ภาค 15', province: 'ระยอง', district: 'ระยอง', branch: 'แพชชั่น ช้อปปิ้ง เดสติเนชั่น' },
  { region: 'ภาค 15', province: 'ระยอง', district: 'ระยอง', branch: 'นิคมพัฒนา ระยอง' },
  { region: 'ภาค 15', province: 'ระยอง', district: 'ระยอง', branch: 'เซ็นทรัล ระยอง' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'โรบินสัน สมุทรปราการ' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'นิคมอุตสาหกรรมบางพลี' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'สมุทรปราการ' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'บางพลี' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'บางบ่อ' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'คลองด่าน' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'ถนนกิ่งแก้ว-สุวรรณภูมิ' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'เมืองสมุทร' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'นิคมอุตสาหกรรมบางปู' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'เมกาบางนา' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'บิ๊กซี ศรีนครินทร์' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'มาร์เก็ตวิลเลจ สุวรรณภูมิ' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 1', branch: 'เทศบาลแพรกษา (นิคมอุตสาหกรรมบางปู)' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 2', branch: 'บิ๊กซี สำโรง 2' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 2', branch: 'สำโรง' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 2', branch: 'พระประแดง' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 2', branch: 'สุขสวัสดิ์' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 2', branch: 'ปู่เจ้าสมิงพราย' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 2', branch: 'อิมพีเรียล เวิลด์ สำโรง ' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 2', branch: 'พระสมุทรเจดีย์' },
  { region: 'ภาค 15', province: 'สมุทรปราการ', district: 'สมุทรปราการ 2', branch: 'บิ๊กซี สุขสวัสดิ์' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 1', branch: 'ชุมพร' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 1', branch: 'ท่าแซะ' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 1', branch: 'ปากน้ำชุมพร' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 1', branch: 'ปะทิว' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 1', branch: 'มาบอำมฤต' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 1', branch: 'ศูนย์การค้าโอเชี่ยนคอมเพล็กซ์ ชุมพร' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 2', branch: 'สวี' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 2', branch: 'หลังสวน' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 2', branch: 'ปฐมพร' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 2', branch: 'ทุ่งตะโก' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 2', branch: 'ละแม' },
  { region: 'ภาค 16', province: 'ชุมพร', district: 'ชุมพร 2', branch: 'พะโต๊ะ' },
  { region: 'ภาค 16', province: 'ระนอง', district: 'ชุมพร 1', branch: 'ระนอง' },
  { region: 'ภาค 16', province: 'ระนอง', district: 'ชุมพร 1', branch: 'กระบุรี' },
  { region: 'ภาค 16', province: 'ระนอง', district: 'ชุมพร 1', branch: 'ถนนเรืองราษฎร์' },
  { region: 'ภาค 16', province: 'ระนอง', district: 'ชุมพร 1', branch: 'สุขสำราญ' },
  { region: 'ภาค 16', province: 'พังงา', district: 'พังงา', branch: 'พังงา' },
  { region: 'ภาค 16', province: 'พังงา', district: 'พังงา', branch: 'โคกกลอย' },
  { region: 'ภาค 16', province: 'พังงา', district: 'พังงา', branch: 'ท้ายเหมือง' },
  { region: 'ภาค 16', province: 'พังงา', district: 'พังงา', branch: 'คุระบุรี' },
  { region: 'ภาค 16', province: 'พังงา', district: 'พังงา', branch: 'ทับปุด' },
  { region: 'ภาค 16', province: 'พังงา', district: 'พังงา', branch: 'ย่านยาว' },
  { region: 'ภาค 16', province: 'พังงา', district: 'พังงา', branch: 'เขาหลัก' },
  { region: 'ภาค 16', province: 'พังงา', district: 'พังงา', branch: 'เกาะยาว' },
  { region: 'ภาค 16', province: 'พังงา', district: 'พังงา', branch: 'ตะกั่วป่า (ย่านยาว)' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'ภูเก็ต' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'ป่าตอง' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'ถลาง' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'ห้าแยกฉลอง' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'เชิงทะเล' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'สามกอง' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'เซ็นทรัลภูเก็ต เฟสติวัล' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'ถนนเทพกระษัตรี' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'กะทู้' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'ถนนพูนผล' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'สี่แยกท่าเรือ' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'กะรน' },
  { region: 'ภาค 16', province: 'ภูเก็ต', district: 'ภูเก็ต', branch: 'เทศบาลวิชิต (ภูเก็ต)' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'สุราษฎร์ธานี' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'บ้านนาสาร' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'เกาะสมุย' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'กาญจนดิษฐ์' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'เวียงสระ' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'ดอนสัก' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'ถนนราษฎร์อุทิศ' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'บ่อผุด' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'เซ็นทรัล สมุย' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'เกาะพะงัน' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'ขุนทะเล' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'บ้านนาเดิม' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'ละไม' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'เซ็นทรัล สุราษฎร์ธานี' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 1', branch: 'ถนนกาญจนวิถี' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'ไชยา' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'พุนพิน' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'พระแสง' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'ท่าฉาง' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'ท่าชนะ' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'คีรีรัฐนิคม' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'พนม' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'เคียนซา' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'บางสวรรค์' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'วิภาวดี' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'ชัยบุรี' },
  { region: 'ภาค 16', province: 'สุราษฎร์ธานี', district: 'สุราษฎร์ธานี 2', branch: 'บ้านตาขุน' },
  { region: 'ภาค 17', province: 'กระบี่', district: 'กระบี่', branch: 'กระบี่' },
  { region: 'ภาค 17', province: 'กระบี่', district: 'กระบี่', branch: 'คลองท่อม' },
  { region: 'ภาค 17', province: 'กระบี่', district: 'กระบี่', branch: 'อ่าวลึก' },
  { region: 'ภาค 17', province: 'กระบี่', district: 'กระบี่', branch: 'เหนือคลอง' },
  { region: 'ภาค 17', province: 'กระบี่', district: 'กระบี่', branch: 'เกาะลันตา' },
  { region: 'ภาค 17', province: 'กระบี่', district: 'กระบี่', branch: 'อ่าวนาง' },
  { region: 'ภาค 17', province: 'กระบี่', district: 'กระบี่', branch: 'ตลาดเก่า' },
  { region: 'ภาค 17', province: 'กระบี่', district: 'กระบี่', branch: 'ลำทับ' },
  { region: 'ภาค 17', province: 'กระบี่', district: 'กระบี่', branch: 'โลตัส กระบี่ ' },
  { region: 'ภาค 17', province: 'กระบี่', district: 'กระบี่', branch: 'ปลายพระยา' },
  { region: 'ภาค 17', province: 'กระบี่', district: 'กระบี่', branch: 'เขาพนม' },
  { region: 'ภาค 17', province: 'ตรัง', district: 'ตรัง', branch: 'ตรัง' },
  { region: 'ภาค 17', province: 'ตรัง', district: 'ตรัง', branch: 'ย่านตาขาว' },
  { region: 'ภาค 17', province: 'ตรัง', district: 'ตรัง', branch: 'กันตัง' },
  { region: 'ภาค 17', province: 'ตรัง', district: 'ตรัง', branch: 'ห้วยยอด' },
  { region: 'ภาค 17', province: 'ตรัง', district: 'ตรัง', branch: 'โรบินสัน ตรัง' },
  { region: 'ภาค 17', province: 'ตรัง', district: 'ตรัง', branch: 'ทุ่งยาว' },
  { region: 'ภาค 17', province: 'ตรัง', district: 'ตรัง', branch: 'รัษฎา' },
  { region: 'ภาค 17', province: 'ตรัง', district: 'ตรัง', branch: 'สนามกีฬา ตรัง' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'นครศรีธรรมราช' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'ปากพนัง' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'สิชล' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'ท่าศาลา' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'เชียรใหญ่' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'หัวไทร' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'ขนอม' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'ตลาดหัวอิฐ' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'ลานสกา' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'โรบินสัน นครศรีธรรมราช' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'พรหมคีรี' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'เซ็นทรัล นครศรีธรรมราช' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'นาหลวง' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 1', branch: 'มหาวิทยาลัยวลัยลักษณ์ (ท่าศาลา)' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 2', branch: 'ทุ่งสง' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 2', branch: 'ร่อนพิบูลย์' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 2', branch: 'ฉวาง' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 2', branch: 'ชะอวด' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 2', branch: 'จันดี' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 2', branch: 'ทุ่งใหญ่' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 2', branch: 'ศูนย์การค้าไทยสมบูรณ์ทุ่งสง' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 2', branch: 'พิปูน' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 2', branch: 'ถ้ำพรรณรา' },
  { region: 'ภาค 17', province: 'นครศรีธรรมราช', district: 'นครศรีธรรมราช 2', branch: 'บางขัน' },
  { region: 'ภาค 17', province: 'พัทลุง', district: 'พัทลุง', branch: 'พัทลุง' },
  { region: 'ภาค 17', province: 'พัทลุง', district: 'พัทลุง', branch: 'ปากพะยูน' },
  { region: 'ภาค 17', province: 'พัทลุง', district: 'พัทลุง', branch: 'เขาชัยสน' },
  { region: 'ภาค 17', province: 'พัทลุง', district: 'พัทลุง', branch: 'ควนขนุน' },
  { region: 'ภาค 17', province: 'พัทลุง', district: 'พัทลุง', branch: 'ตะโหมด' },
  { region: 'ภาค 17', province: 'พัทลุง', district: 'พัทลุง', branch: 'ป่าพะยอม' },
  { region: 'ภาค 17', province: 'พัทลุง', district: 'พัทลุง', branch: 'ป่าบอน' },
  { region: 'ภาค 17', province: 'พัทลุง', district: 'พัทลุง', branch: 'ถนนนิวาส' },
  { region: 'ภาค 17', province: 'พัทลุง', district: 'พัทลุง', branch: 'ศรีนครินทร์ (พัทลุง)' },
  { region: 'ภาค 18', province: 'นราธิวาส', district: 'นราธิวาส', branch: 'นราธิวาส' },
  { region: 'ภาค 18', province: 'นราธิวาส', district: 'นราธิวาส', branch: 'สุไหงโก-ลก' },
  { region: 'ภาค 18', province: 'นราธิวาส', district: 'นราธิวาส', branch: 'ตากใบ' },
  { region: 'ภาค 18', province: 'นราธิวาส', district: 'นราธิวาส', branch: 'รือเสาะ' },
  { region: 'ภาค 18', province: 'นราธิวาส', district: 'นราธิวาส', branch: 'ตันหยงมัส' },
  { region: 'ภาค 18', province: 'นราธิวาส', district: 'นราธิวาส', branch: 'สุไหงปาดี' },
  { region: 'ภาค 18', province: 'นราธิวาส', district: 'นราธิวาส', branch: 'สุคิริน ' },
  { region: 'ภาค 18', province: 'นราธิวาส', district: 'นราธิวาส', branch: 'สุริยะประดิษฐ์' },
  { region: 'ภาค 18', province: 'ปัตตานี', district: 'ปัตตานี', branch: 'ปัตตานี' },
  { region: 'ภาค 18', province: 'ปัตตานี', district: 'ปัตตานี', branch: 'สายบุรี' },
  { region: 'ภาค 18', province: 'ปัตตานี', district: 'ปัตตานี', branch: 'โคกโพธิ์' },
  { region: 'ภาค 18', province: 'ปัตตานี', district: 'ปัตตานี', branch: 'ถนนหนองจิก ปัตตานี' },
  { region: 'ภาค 18', province: 'ยะลา', district: 'ปัตตานี', branch: 'ยะลา' },
  { region: 'ภาค 18', province: 'ยะลา', district: 'ปัตตานี', branch: 'เบตง' },
  { region: 'ภาค 18', province: 'ยะลา', district: 'ปัตตานี', branch: 'บันนังสตา' },
  { region: 'ภาค 18', province: 'ยะลา', district: 'ปัตตานี', branch: 'ยะหา' },
  { region: 'ภาค 18', province: 'ยะลา', district: 'ปัตตานี', branch: 'ผังเมือง 4' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'สงขลา' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'ระโนด ' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'สทิงพระ' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'จะนะ' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'เทพา' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'นาทวี' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'สะบ้าย้อย' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'สิงหนคร' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'โลตัส สงขลา' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'คลองแงะ' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'สะเดา' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 1', branch: 'ปาดังเบซาร์' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 2', branch: 'หาดใหญ่' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 2', branch: 'รัตภูมิ' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 2', branch: 'ศรีภูวนารถ' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 2', branch: 'หาดใหญ่ใน' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 2', branch: 'ควนเนียง' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 2', branch: 'ถนนลพบุรีราเมศวร์' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 2', branch: 'ราษฎร์อุทิศ หาดใหญ่' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 2', branch: 'บ้านพรุ' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 2', branch: 'เซ็นทรัล หาดใหญ่' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 2', branch: 'ถนนกองบิน 56 (หาดใหญ่)' },
  { region: 'ภาค 18', province: 'สงขลา', district: 'สงขลา 2', branch: 'บิ๊กซี เอ็กซ์ตร้า หาดใหญ่' },
  { region: 'ภาค 18', province: 'สตูล', district: 'สงขลา 2', branch: 'สตูล' },
  { region: 'ภาค 18', province: 'สตูล', district: 'สงขลา 2', branch: 'ละงู' },
  { region: 'ภาค 18', province: 'สตูล', district: 'สงขลา 2', branch: 'ท่าแพ (สตูล)' },
  { region: 'ภาค 18', province: 'ปัตตานี', district: 'ปัตตานี', branch: 'กะพ้อ (สายบุรี)' },
  { region: 'ภาค 18', province: 'ปัตตานี', district: 'ปัตตานี', branch: 'ทุ่งยางแดง (ถนนหนองจิก ปัตตานี)' },
  { region: 'ภาค 18', province: 'ยะลา', district: 'ปัตตานี', branch: 'กรงปินัง (ผังเมือง 4)' },
  { region: 'ภาค 18', province: 'ยะลา', district: 'ปัตตานี', branch: 'ธารโต (บันนังสตา)' },
  ];

  return mockData;
};

// Function to parse CSV file
async function parseLocationCSV(csvText: string): Promise<LocationCSVRow[]> {
  const lines = csvText.trim().split('\n');
  // Skip header line, parse data lines
  return lines.slice(1).map(line => {
    const columns = line.split('\t'); // Using tab delimiter based on your example
    return {
      region: columns[0]?.trim() || '',
      province: columns[1]?.trim() || '',
      district: columns[2]?.trim() || '',
      branch: columns[3]?.trim() || ''
    };
  }).filter(row => row.region && row.province); // Filter out empty rows
}

// Load location data from single CSV file
async function loadLocationCSVData(): Promise<LocationCSVRow[]> {
  try {
    console.log('Attempting to load location data from public/data/locations.csv...');
    
    const response = await fetch('/data/locations.csv');
    if (!response.ok) {
      throw new Error('locations.csv not found');
    }

    const csvText = await response.text();
    const data = await parseLocationCSV(csvText);
    
    console.log('Successfully loaded location CSV data:', data.length, 'rows');
    return data;
    
  } catch (error) {
    console.warn('CSV file not found or failed to load, using mock data:', error);
    console.log('To use real data, please add locations.csv to public/data/ with columns: ภาค, จังหวัด, เขต, หน่วยให้บริการ');
    
    return generateLocationMockData();
  }
}

// Transform CSV data into structured location data
function transformToLocationData(csvData: LocationCSVRow[]): LocationData {
  // Extract unique regions
  const uniqueRegions = [...new Set(csvData.map(row => row.region))];
  const regions: Region[] = uniqueRegions.map((regionName, index) => ({
    id: `region_${index + 1}`,
    name: regionName
  }));

  // Extract unique provinces with region relationships
  const uniqueProvinces = [...new Set(csvData.map(row => `${row.region}|${row.province}`))];
  const provinces: Province[] = uniqueProvinces.map((combo, index) => {
    const [regionName, provinceName] = combo.split('|');
    const region = regions.find(r => r.name === regionName);
    return {
      id: `province_${index + 1}`,
      name: provinceName,
      regionId: region?.id || 'region_1'
    };
  });

  // Extract unique districts with province relationships
  const uniqueDistricts = [...new Set(csvData.map(row => `${row.province}|${row.district}`))];
  const districts: District[] = uniqueDistricts.map((combo, index) => {
    const [provinceName, districtName] = combo.split('|');
    const province = provinces.find(p => p.name === provinceName);
    return {
      id: `district_${index + 1}`,
      name: districtName,
      provinceId: province?.id || 'province_1'
    };
  });

  // Extract branches with district relationships
  const branches: Branch[] = csvData.map((row, index) => {
    const district = districts.find(d => d.name === row.district);
    return {
      id: `branch_${index + 1}`,
      name: row.branch,
      districtId: district?.id || 'district_1'
    };
  });

  return { regions, provinces, districts, branches };
}

// Global variables for easy access
let locationDataCache: LocationData | null = null;
let regionsData: Region[] = [];
let provincesData: Province[] = [];
let districtsData: District[] = [];
let branchesData: Branch[] = [];

// Initialize and cache location data
export async function initializeLocationData(): Promise<LocationData> {
  if (!locationDataCache) {
    const csvData = await loadLocationCSVData();
    locationDataCache = transformToLocationData(csvData);
    
    // Set global variables for easy access
    regionsData = locationDataCache.regions;
    provincesData = locationDataCache.provinces;
    districtsData = locationDataCache.districts;
    branchesData = locationDataCache.branches;
    
    console.log('Location data initialized:', {
      regions: regionsData.length,
      provinces: provincesData.length,
      districts: districtsData.length,
      branches: branchesData.length
    });
  }
  
  return locationDataCache;
}

// Easy access variables - these will be populated after initializeLocationData() is called
export const getRegions = (): Region[] => regionsData;
export const getProvinces = (): Province[] => provincesData;
export const getDistricts = (): District[] => districtsData;
export const getBranches = (): Branch[] => branchesData;

// Get full location data
export const getLocationData = async (): Promise<LocationData> => {
  return await initializeLocationData();
};

// Clear cache function (useful for development)
export function clearLocationDataCache(): void {
  locationDataCache = null;
  regionsData = [];
  provincesData = [];
  districtsData = [];
  branchesData = [];
}
